[package]
name = "torrential"
version = "4.0.0"
edition = "2021"

[features]
default = ["gtk4_6"]
gtk4_6 = ["gtk/v4_6"]
gtk4_10 = ["gtk4_6", "gtk/v4_10"]

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.6", package = "gtk4" }
granite = { version = "0.2.1", package = "granite-rs", features = ["v7_2"] }
once_cell = "1.0"
int-enum = "0.5.0"
cfg-if = "1.0.0"

